apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hfproxy
  namespace: default
spec:
template:
  metadata:
    annotations:
      autoscaling.knative.dev/maxScale: "1"
      autoscaling.knative.dev/minScale: "1"
  spec:
    containers:
    - image: harbor-infp.com:14444/ais-system47/hfproxy:latest
      ports:
      - containerPort: 30555
      readinessProbe:
        httpGet:
          host: 127.0.0.1
          port: 30555
          path: "/health"