server:
  port: "30418"
log:
  level: "TRACE"
  defaultConfigName: "ihub.log"
routes:
- moudle: "appstore"
  target: "http://127.0.0.1:7070"
- moudle: "datacenter"
  target: "http://127.0.0.1:6060"
DB:
  NAME: "dev"
  HOST: "127.0.0.1"
  PORT: 3306
  USER: "root"
  PASSWD: "306d022030da786844efbe1e68787fbd5129c71f40b571a44a5fe9bbb2153726a446e829022100eb9ff14b84b41de27ac1c22f140e706dbdbe2e6fa5f7616883aaebd43d17245104200c516160b0e091baca985484a985f8774c297def1a7f0b8fa56dd3c3be8f8b6b04043ffb8a9a"
  CHARSET: "utf8"
  SM2PRIVATEFILE: "gosm2Private.pem"
runmode: "out"
midwares:
- midware: "logger"
- midware: "trace"
- midware: "inout"
- midware: "auth"
modules:
  account-server: '{"zh-CN": "用户管理","en-US": "account-server"}'
  model-deploy: '{"zh-CN": "模型服务","en-US": "model-deploy"}'
  appstore: '{"zh-CN": "应用商店管理","en-US": "appstore"}'
  api-security: '{"zh-CN": "API授权","en-US": "api-security"}'
operators:
  modify_group_owner: '{"zh-CN": "资源修改","en-US": "modify_group_owner"}'
  update: '{"zh-CN": "应用部署","en-US": "update"}'
  delete: '{"zh-CN": "应用删除","en-US": "delete"}'
  create-node-deploy: '{"zh-CN": "节点部署","en-US": "create-node-deploy"}'
  delete-node-deploy: '{"zh-CN": "节点部署删除","en-US": "delete-node-deploy"}'
  createNativeResource: '{"zh-CN": "原生部署","en-US": "createNativeResource"}'
  deleteNativeResource: '{"zh-CN": "原生部署删除","en-US": "deleteNativeResource"}'
  create-graph: '{"zh-CN": "服务编排创建","en-US": "create-graph"}'
  delete-graph: '{"zh-CN": "服务编排删除","en-US": "delete-graph"}'
  create-share-service: '{"zh-CN": "细粒度服务创建","en-US": "create-share-service"}'
  delete-share-service: '{"zh-CN": "细粒度服务删除","en-US": "delete-share-service"}'
  traffic: '{"zh-CN": "创建/修改流量调控","en-US": "traffic"}'
  traffic-rollback: '{"zh-CN": "流量回滚","en-US": "traffic-rollback"}'
  promote: '{"zh-CN": "服务转正","en-US": "promote"}'
  app_transfer: '{"zh-CN": "应用商店所属权转移","en-US": "app_transfer"}'
  helm_deploy: '{"zh-CN": "应用商店helm部署","en-US": "helm_deploy"}'
  app_auth: '{"zh-CN": "应用商店权限更改","en-US": "app_auth"}'
  app_delete: '{"zh-CN": "应用商店删除","en-US": "app_delete"}'
  api_delete: '{"zh-CN": "签名删除","en-US": "api_delete"}'
  api_create: '{"zh-CN": "签名生成","en-US": "api_create"}'
  api_update: '{"zh-CN": "签名更新","en-US": "api_update"}'
moduleOperate:
  account-server: ['modify_group_owner']
  model-deploy: ['update', 'delete', 'create-node-deploy', 'delete-node-deploy', 'createNativeResource', 'deleteNativeResource', 'create-graph', 'delete-graph', 'create-share-service', 'delete-share-service', 'traffic', 'traffic-rollback', 'promote']
  appstore: ['app_transfer', 'app_auth', 'app_delete']
  api-security: ['create', 'update', 'delete']
appstoreMap:
  v1/helm/helm_deploy: 'helm_deploy'
  v1/store/app_auth: 'app_auth'
  v1/store/app_transfer: 'app_transfer'
  v1/store/app_delete: 'app_delete'
  v1/token/create: 'api_create'
  v1/token/update: 'api_update'
  v1/token/delete: 'api_delete'